### PR TITLE
Allow tiller namespace override via evar

### PR DESCRIPTION
**Pull request by JoseAlban**
Use-case: shipcat was assuming tiller-namespace to be the same namespace in which service would be deployed - and I needed to decouple those concepts in order to use shipcat for deploying on my local kube cluster.

I'm happy to listen why this is not a good idea - but it was immediately useful for me.
Maybe it could be a CLI arg, but tiller is going to disappear soon, so that arg can also be used to invalidate that PR in the future.

Or, this can be wiped out as part of a tiller-removal refactor.

### CODE REVIEW

**Comment by clux** [comment]
The idea is to ensure we have a local rbac'd tiller. You can install tiller into the namespace like our cluster standard using: https://github.com/Babylonpartners/shipcat/blob/master/examples/tiller.yml .

**Comment by JoseAlban** [comment]
It's definitely possible to install it like we have on our specific case - but thinking about a more generic approach here, since it's an open-source tool - it'd be nice to be flexible. Unless it's a bad practice to have tiller on `kube-system` for some reason, but for local development it's quite helpful as it minimises custom setup.

**Comment by clux** [comment]
Well, it was kind of bad practice earlier since you couldn't scope RBAC rules. But while I agree it would simplify things a bit, tiller is going away entirely (see https://github.com/helm/community/blob/master/helm-v3/000-helm-v3.md and #11 ) so am inclined not to make changes to tiller integration until that's done.

**Comment by JoseAlban** [comment]
This would soon be obsolete indeed.

**Pull request closed without merging**
